services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=pfcime2025
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      - neo4j
      - ollama
    command: sleep infinity

  neo4j:
    image: neo4j:5.9.0
    environment:
      - NEO4J_AUTH=neo4j/pfcime2025
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  ollama_data: 