services:
  app:
    build: .
    volumes:
      - .:/app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=pfcime2025
      - OLLAMA_HOST=http://ollama:11434
    depends_on:
      neo4j:
        condition: service_healthy
    command: sleep infinity

  neo4j:
    build:
      context: .
      dockerfile: Dockerfile.neo4j
    environment:
      - NEO4J_AUTH=neo4j/pfcime2025
      - NEO4J_apoc_export_file_enabled=true
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_dbms_security_procedures_unrestricted=n10s.*
      - NEO4J_dbms_security_procedures_allowlist=n10s.*
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
      - neo4j_import:/var/lib/neo4j/import
      - ./ontology/uco-ttl:/uco-ttl:ro 
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "pfcime2025", "RETURN 1"]
      interval: 10s
      timeout: 5s
      retries: 5

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    command: serve

  flask-server:
    build: .
    volumes:
      - .:/app
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=pfcime2025
      - OLLAMA_HOST=http://ollama:11434
      - FLASK_ENV=development
    depends_on:
      neo4j:
        condition: service_healthy
    command: python server/app.py
    ports:
      - "5001:5001"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password

  mq-consumer:
    build: .
    volumes:
      - .:/app
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_QUEUE=alerts
      - GENERATE_PLAYBOOK_URL=http://flask-server:5001/generate-playbook
    depends_on:
      - flask-server
      - rabbitmq
    command: python mq/consumer.py

volumes:
  neo4j_data:
  neo4j_logs:
  neo4j_import:
  ollama_data: